### ISSUE TITLE
Clearer Installation Instructions

### ISSUE THREAD

**Issue by UndeclaredVariable** [brendanheywood/moodle-mod_cpdlogbook#22]
Cloning the repository saves the folder as `moodle-mod_cpdlogbook`, but Moodle doesn't recognize the plugin unless the foler is called `cpdlogbook`. This should be made clear in the readme.

**Comment by brendanheywood** [comment]
+1 best kind of issue :)

Some example text:

https://github.com/catalyst/moodle-auth_saml2#installation
